export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const ORDER_BURGER_SUBMITTED = 'ORDER_BURGER_SUBMITTED';
export const ORDER_BURGER_SUCCEEDED = 'ORDER_BURGER_SUCCEEDED';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
